version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - "${PORT}"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
